"use client";

import { EmptyState } from "@/components/ui/EmptyState";
import { PageHeader } from "@/components/ui/PageHeader";

export default function TasksPage() {
  return (
    <div className="space-y-6 reveal-animation">
      <PageHeader
        eyebrow="Tasks"
        title="Task Management"
        description="Manage manual tasks and tasks generated by the CRM agents."
      />

      <EmptyState 
        title="Coming Soon" 
        description="The task management feature is currently under development. Please check back later." 
      />
    </div>
  );
}
